name: Check formatting

on: push

jobs:
  check_formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - uses: abatilo/actions-poetry@v2
      - name: Cache venv created by poetry (configured to be in '.venv')
        uses: actions/cache@v3
        with:
          path: ./.venv
          key: venv-${{ runner.os }}-${{ hashFiles('poetry.lock') }}
      - name: Install dependencies
        run: poetry install --no-root --with dev
      - name: Run formatter
        run: |
          poetry run tan --check . --line-length 120 --verbose
      - name: Run Linter
        run: |
          poetry run ruff check .
